#!/bin/bash

# OpenWrt Builder 初始化脚本
# 帮助用户快速设置 GitHub 仓库

echo "==================================="
echo "OpenWrt Builder 初始化脚本"
echo "JDCloud AX1800 Pro 专用"
echo "OpenWrt v25.12.2 (最新稳定版)"
echo "==================================="
echo ""

# 检查 git 是否安装
if ! command -v git &> /dev/null; then
    echo "错误: 未检测到 git，请先安装 git"
    exit 1
fi

echo "✓ Git 已安装"
echo ""

# 显示仓库结构
echo "当前仓库结构:"
echo ""
echo "openwrt-builder/"
echo "├── .github/"
echo "│   └── workflows/"
echo "│       └── build-openwrt.yml    # GitHub Actions 工作流"
echo "├── config/"
echo "│   └── qualcommax_ipq60xx.config  # OpenWrt 配置文件"
echo "├── scripts/"
echo "│   └── modify-config.sh         # 配置修改工具"
echo "├── .gitignore                   # Git 忽略文件"
echo "├── README.md                    # 详细说明文档"
echo "├── QUICKSTART.md               # 快速开始指南"
echo "├── PACKAGES.md                 # 软件包列表"
echo "└── init.sh                     # 本初始化脚本"
echo ""

echo "接下来你需要做的："
echo ""
echo "1. 在 GitHub 上创建一个新的仓库（例如: my-openwrt-builder）"
echo ""
echo "2. 将本地文件推送到 GitHub："
echo ""
echo "   cd /d/Desktop/固件/openwrt-builder"
echo "   git init"
echo "   git add ."
echo "   git commit -m '初始化 OpenWrt Builder'"
echo "   git branch -M main"
echo "   git remote add origin https://github.com/你的用户名/my-openwrt-builder.git"
echo "   git push -u origin main"
echo ""
echo "3. 在 GitHub 仓库页面，点击 Actions 标签"
echo ""
echo "4. 点击 'Build OpenWrt for JDCloud AX1800 Pro' 工作流"
echo ""
echo "5. 点击 'Run workflow' 按钮开始编译"
echo ""
echo "==================================="
echo ""
echo "需要帮助？"
echo ""
echo "- 查看 QUICKSTART.md 了解快速开始"
echo "- 查看 README.md 了解详细说明"
echo "- 查看 PACKAGES.md 了解可用软件包"
echo ""
echo "==================================="
echo ""
echo "当前配置的默认软件包："
echo ""
grep "CONFIG_PACKAGE_.*=y" config/qualcommax_ipq60xx.config | sed 's/CONFIG_PACKAGE_/  ✓ /' | sed 's/=y//' | head -20
echo "  ... (更多)"
echo ""
echo "==================================="
echo ""
echo "开始使用："
echo ""
echo "1. 编辑 config/qualcommax_ipq60xx.config 添加你想要的软件包"
echo ""
echo "2. 使用脚本添加软件包："
echo "   ./scripts/modify-config.sh -a luci-app-openclash"
echo ""
echo "3. 提交更改："
echo "   git add ."
echo "   git commit -m '添加 OpenClash'"
echo "   git push"
echo ""
echo "4. 在 GitHub Actions 运行编译"
echo ""
echo "祝你编译顺利！🚀"
echo ""
